import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getAlerts } from "../api/api";
import LoadingButton from "../components/LoadingButton";
import SkeletonLoader from "../components/SkeletonLoader";

const Alerts = () => {
    const [alerts, setAlerts] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    const fetchAlerts = async () => {
        try {
            setLoading(true);
            const response = await getAlerts();
            setAlerts(response.data.data);
            setError("");
        }
        catch (err) {
            setError("Failed to load alerts");
            console.log(err);
        }
        finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchAlerts();
    }, []);

    const getSeverityClass = (severity) => {
        if (severity === "HIGH") {
            return "bg-red-100 text-red-700";
        }

        if (severity === "MEDIUM") {
            return "bg-amber-100 text-amber-700";
        }

        return "bg-green-100 text-green-700";
    };

    return (
        <div className="min-h-screen bg-slate-100 p-8">
            <div className="mb-6">
                <h1 className="text-3xl font-bold text-slate-900">Alerts</h1>
                <p className="mt-2 text-slate-600">
                    Risk alerts generated by the risk engine.
                </p>
            </div>

            {loading && (
                <>
                    <div className="mb-8">
                        <LoadingButton text="Loading alerts..." />
                    </div>

                    <SkeletonLoader type="table" />
                </>
            )}

            {error && <p className="font-semibold text-red-600">{error}</p>}

            {!loading && !error && (
                <div className="overflow-hidden rounded-2xl bg-white shadow">
                    <div className="overflow-x-auto">
                        <table className="w-full border-collapse text-left text-sm">
                            <thead className="bg-slate-50 text-slate-600">
                                <tr>
                                    <th className="px-5 py-4">Trader</th>
                                    <th className="px-5 py-4">Stock</th>
                                    <th className="px-5 py-4">Alert Type</th>
                                    <th className="px-5 py-4">Severity</th>
                                    <th className="px-5 py-4">Risk Score</th>
                                    <th className="px-5 py-4">Status</th>
                                    <th className="px-5 py-4">Created</th>
                                    <th className="px-5 py-4">Action</th>
                                </tr>
                            </thead>

                            <tbody className="divide-y divide-slate-100">
                                {alerts.length === 0 ? (
                                    <tr>
                                        <td className="px-5 py-4" colSpan="8">
                                            No alerts found.
                                        </td>
                                    </tr>
                                ) : (
                                    alerts.map((alert) => (
                                        <tr className="hover:bg-slate-50" key={alert._id}>
                                            <td className="px-5 py-4">
                                                <div className="font-medium text-slate-900">
                                                    {alert.traderName}
                                                </div>
                                                <div className="text-xs text-slate-500">
                                                    {alert.traderId}
                                                </div>
                                            </td>

                                            <td className="px-5 py-4 font-semibold">
                                                {alert.stockSymbol}
                                            </td>

                                            <td className="px-5 py-4">{alert.alertType}</td>

                                            <td className="px-5 py-4">
                                                <span
                                                    className={`rounded-full px-3 py-1 text-xs font-bold ${getSeverityClass(alert.severity)}`}
                                                >
                                                    {alert.severity}
                                                </span>
                                            </td>

                                            <td className="px-5 py-4 font-semibold">
                                                {alert.riskScore}
                                            </td>

                                            <td className="px-5 py-4">{alert.status}</td>

                                            <td className="px-5 py-4 text-slate-500">
                                                {new Date(alert.createdAt).toLocaleString()}
                                            </td>

                                            <td className="px-5 py-4">
                                                <Link
                                                    className="font-semibold text-blue-600 hover:underline"
                                                    to={`/alerts/${alert._id}`}
                                                >
                                                    View
                                                </Link>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Alerts;